# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22.12-alpine AS builder

# Install the build dependencies
RUN apk add --no-cache build-base python3

# Set working directory
WORKDIR /app

# Copy the package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy the source files and build the project
COPY tsconfig.json tsconfig.base.json ./
COPY src/ src/
RUN npm run build

# Create a new image from the built files
FROM node:22.12-alpine AS runner

# Set working directory
WORKDIR /app

# Copy the compiled files and package configuration from the builder stage
COPY --from=builder /app/dist/ ./dist/
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm ci --ignore-scripts --omit=dev

# Set environment variable for the access token (to be set when running the container)
ENV OSC_ACCESS_TOKEN=your_access_token_here

# Define the entry point of the application
ENTRYPOINT ["node", "dist/index.js"]